#!/bin/zsh
#
# Find unused Perl functions in a source tree, using the current directory as
# the search root.  Ignores functions whose names are spelled entirely with
# uppercase letters.
#
# ---------------------------------------------------------------------------
#
# This software is distributed under the MIT License.
# 
# Copyright (c) 2014 Colin Wetherbee
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# 

funcs=(
    $(ack-grep --perl '^sub ' |
      sed 's/^.*:.*:sub //; s/ .*$//;' |
      grep -Ev '^[[:upper:]]*$')
)

printed_header=0

for func in $funcs
do
    if ! ack-grep --perl -1 "(?<!^sub )$func\\b" >/dev/null
    then
        if [[ $printed_header -eq 0 ]]
        then
            print "Unused functions:"
            printed_header=1
        fi
        print "\t$func"
    fi
done
