#!/bin/zsh
#
# This script retrieves a list of blackhole IP addresses and uses the
# iptables(8) utility to blackhole those IP addresses.  Of course, This
# script requires that kernel support for iptables is enabled.

BLACKHOLES_URL="https://raw.github.com/cww/tools/master/blackholes/blackholes.txt"

ips=( $(curl -s "$BLACKHOLES_URL") )
if [[ $? -ne 0 ]]
then
    print "ERROR: Unable to retrieve blackhole list!"
    exit 1
fi

for ip in $ips
do
    # `iptables -C` requires iptables after squeeze
    iptables -C INPUT -s "$ip" -j DROP 2>& /dev/null
    if [[ $? -eq 0 ]]
    then
        print "INFO: IP $ip is already in blackhole list; not adding."
    else
        cmd=(iptables -I INPUT -s "$ip" -j DROP)
        print "INFO: Running command: $cmd"
        $cmd
    fi
done

exit 0
