#!/bin/zsh
#
# The MIT License (MIT)
#
# Copyright (c) 2013, 2015 Colin Wetherbee
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
###########################################################################
#
# This script blacklists the IP addresses and network masks stored in the
# blackholes file.  Requires iptables and kernel support thereof.

# Get current blackholes from iptables; /32 addresses have their netmask
# removed.
cur_bls=( $(iptables -S INPUT | perl -nE 'm|-s\s+(\S+?)(?:/32)?\s| && say $1') )
ips=( $(cat $(dirname $0:A)/blackholes.txt) )

for ip in $ips; do
    if [[ ${cur_bls[(i)$ip]} -le ${#cur_bls} ]]; then
        print "INFO: IP $ip is already in blackhole list; not adding."
    else
        cmd=(iptables -I INPUT -s "$ip" -j DROP)
        print "INFO: Running command: $cmd"
        $cmd
    fi
done

exit 0
