#!/bin/zsh
#
# This script retrieves a list of blackhole IP addresses and uses the
# ip(8) utility to blackhole those IP addresses.

BLACKHOLES_URL="https://raw.github.com/cww/tools/master/blackholes/blackholes.txt"

ips=( $(curl -s "$BLACKHOLES_URL") )
if [[ $? -ne 0 ]]
then
    print "ERROR: Unable to retrieve blackhole list!"
    exit 1
fi

for ip in $ips
do
    ip route list | grep "^blackhole $ip" > /dev/null
    if [[ $? -eq 0 ]]
    then
        print "INFO: IP $ip is already in blackhole list; not adding."
    else
        cmd=(ip route add blackhole $ip)
        print "INFO: Running command: $cmd"
        $cmd
    fi
done

exit 0
