#!/bin/zsh
#
#The MIT License (MIT)
#
#Copyright (c) 2013 Colin Wetherbee
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in
#all copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#THE SOFTWARE.

BLACKHOLES_FILE=blackholes.txt
TMP_FILE=.blackholes.txt

if [[ ! -r $BLACKHOLES_FILE ]]
then
    print "Blackholes file '$BLACKHOLES_FILE' not found" >&2
    exit 1
fi

files=(/var/log/auth.log*)
text_files=($BLACKHOLES_FILE)
gzip_files=()

for file in $files
do
    # Get the file's MIME type
    type=$(file -ib "$file" | sed 's/;.*$//')
    print "$file: $type"
    if [[ $type == "text/plain" ]]
    then
        text_files+=$file
    elif [[ $type == "application/gzip" ]]
    then
        gzip_files+=$file
    else
        print "Unknown file type '$type' for file: $file" >&2
    fi
done

zcat $gzip_files | ./print_failures $text_files > "$TMP_FILE"
mv "$TMP_FILE" "$BLACKHOLES_FILE"
